version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kodigos-dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/kodigos-dev
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  pgdata:
